export const translateFormLabel = {
  translations: {
    "fr": {
      "Registration Form": "Formulaire d'inscription",
      "First Name": "Prénom",
      "Middle Name (optional)": "Deuxième prénom (facultatif)",
      "Last Name": "Nom de famille",
      "Gender": "Sexe",
      "Male": "Homme",
      "Female": "Femme",
      "Date of Birth": "Date de naissance",
      "Mobile Number": "Numéro de téléphone",
      "Email Address (optional)": "Adresse e-mail (facultative)",
      "Profile Photo": "Photo de profil",
      "Country": "Pays",
      "Region": "Région",
      "City": "Ville",
      "ZIP": "Code postal",
      "Division": "Division",
      "Union": "Union",
      "Conference/Field": "Conférence/Champ",
      "Station": "Station",
      "District": "District",
      "Congregation": "Congrégation",
      "Preferred Language": "Langue préférée",
      "Are you a regular participant in the Adventist community?": "Participez-vous régulièrement à la communauté adventiste ?",
      "Are you already baptized as a regular member of the Adventist Church?": "Êtes-vous déjà baptisé comme membre régulier de l’Église adventiste ?",
      "If not, do you expect to be baptized in the future?": "Sinon, prévoyez-vous de vous faire baptiser à l’avenir ?",
      "Select": "Sélectionner",
      "Yes": "Oui",
      "No": "Non",
      "Language": "Langue",
      "Submit": "Soumettre",
      "dear": "cher/ chère",
      "Dear": "Cher/Chère",
      "Close": "Fermer",
      "Your registration has been successfully submitted": "Votre inscription a été soumise avec succès",
      "Welcome to ECD-Adventist Messengers": "Bienvenue chez les Messagers Adventistes de la DCE",
      "Add your name to the Adventist Messenger's Ministry List!": "Ajoutez votre nom à la liste du ministère des messagers adventistes !",
      "Location and membership": "Localisation et adhésion"
    },
    "sw": {
      "Registration Form": "Fomu ya Usajili",
      "First Name": "Jina la Kwanza",
      "Middle Name (optional)": "Jina la Kati (hiari)",
      "Last Name": "Jina la Familia",
      "Gender": "Jinsia",
      "Male": "Mwanaume",
      "Female": "Mwanamke",
      "Date of Birth": "Tarehe ya Kuzaliwa",
      "Mobile Number": "Nambari ya Simu",
      "Email Address (optional)": "Anuani ya Barua Pepe (hiari)",
      "Profile Photo": "Picha ya Wasifu",
      "Country": "Nchi",
      "Region": "Region",
      "City": "Jiji",
      "ZIP": "Kod ya Posta",
      "Division": "Sehemu",
      "Union": "Muungano",
      "Conference/Field": "Mkutano/Uwanja",
      "Station": "Kituo",
      "District": "Wilaya",
      "Congregation": "Kanisa",
      "Preferred Language": "Lugha Inayopendwa",
      "Are you a regular participant in the Adventist community?": "Je, wewe ni mshiriki wa kawaida katika jamii ya Wajifundisha?",
      "Are you already baptized as a regular member of the Adventist Church?": "Je, tayari umebatizwa kama mwanafunzi wa kawaida wa Kanisa la Wajifundisha?",
      "If not, do you expect to be baptized in the future?": "Ikiwa sivyo, je, unatarajia kubatizwa siku zijazo?",
      "Select": "Chagua",
      "Yes": "Ndio",
      "No": "Hapana",
      "Language": "Lugha",
      "Submit": "Tuma",
      "Dear": "Mpendwa",
      "Close": "Funga",
      "Your registration has been successfully submitted": "Usajili wako umetumwa kwa mafanikio",
      "Welcome to ECD-Adventist Messengers": "Karibu kwa Wajumbe wa Waadventista wa ECD",
      "Add your name to the Adventist Messenger's Ministry List!": "Ongeza jina lako kwenye Orodha ya Huduma ya Mjumbe wa Waadventista!",
      "Location and membership": "Mahali na uanachama"
    },
    "rw": {
      "Registration Form": "Ifishi yo Kwiyandikisha",
      "First Name": "Izina rya Mbere",
      "Middle Name (optional)": "Izina ry'inyongera (bihitamo)",
      "Last Name": "Izina ry'Umuryango",
      "Gender": "Igitsina",
      "Male": "Gabo",
      "Female": "Gore",
      "Date of Birth": "Itariki y'Amavuko",
      "Mobile Number": "Numero ya Telephone",
      "Email Address (optional)": "Aderesi ya Email (bihitamo)",
      "Profile Photo": "Ifoto ya Profil",
      "Country": "Igihugu",
      "Region": "Intara",
      "City": "Umujyi",
      "ZIP": "Ikarita y'Itumanaho",
      "Division": "Igice",
      "Union": "Ihuriro",
      "Conference/Field": "Inama/Ubuhanga",
      "Station": "Icyicaro",
      "District": "Akarere",
      "Congregation": "Itorero",
      "Preferred Language": "Ururimi rukundwa",
      "Are you a regular participant in the Adventist community?": "Uri umwe mu bagize umuryango w'Abadivantiste b'umunsi wa karindwi?",
      "Are you already baptized as a regular member of the Adventist Church?": "Ubu urababatijwe nk'umunyamuryango w'itorero ry'Abadivantiste?",
      "If not, do you expect to be baptized in the future?": "Niba atari byo, urateganya kubatizwa mu gihe kizaza?",
      "Select": "Hitamo",
      "Yes": "Yego",
      "No": "Oya",
      "Language": "Ururimi",
      "Submit": "Ohereza",
      "dear": "Mukundwa",
      "close": "funga",
      "your registration has been successfully submitted": "kwiyandikisha kwawe byagenze neza",
      "Welcome to ECD-Adventist Messengers": "Murakaza neza muri ECD-Abamamaza b’Abadiventiste",
      "Add your name to the Adventist Messenger's Ministry List!": "Ongeraho izina ryawe kuri lisiti y’abamamaza b’Abadiventiste!",
      "Location and membership": "Aho ubarizwa n’ubunyamuryango"
    },
    "am": {
      "Registration Form": "የመዝግብ ቅፅ",
      "First Name": "የመጀመሪያ ስም",
      "Middle Name (optional)": "የሚከተለው ስም (አማራጭ)",
      "Last Name": "የመጨረሻ ስም",
      "Gender": "ጾታ",
      "Male": "ወንድ",
      "Female": "ሴት",
      "Date of Birth": "የምርት ቀን",
      "Mobile Number": "የሞባይል ቁጥር",
      "Email Address (optional)": "የኢሜይል አድራሻ (አማራጭ)",
      "Profile Photo": "የመገናኛ ፎቶ",
      "Country": "አገር",
      "Region": "ክፍል",
      "City": "ከተማ",
      "ZIP": "የፖስታ ኮድ",
      "Division": "ክፍል",
      "Union": "እኩልነት",
      "Conference/Field": "ጉባኤ/መስክ",
      "Station": "አካባቢ",
      "District": "ወረዳ",
      "Congregation": "እምነት",
      "Preferred Language": "የተመረጠ ቋንቋ",
      "Are you a regular participant in the Adventist community?": "አዳም ማህበረ ተዋህዶ ውስጥ ዋለው ስለነባቢነት እንደምትኖር ይችላሉ?",
      "Are you already baptized as a regular member of the Adventist Church?": "በአዳም ተዋህዶ ቤተ ክርስቲና ዋለው እንደ ወገን ታድኑን?",
      "If not, do you expect to be baptized in the future?": "እንደ ሌላ አባቶች ከዚያው በተወላጅ ላይ እንደሚያድን ይችላሉ?",
      "Select": "ይምረጡ",
      "Yes": "አዎ",
      "No": "አይደለም",
      "Language": "ቋንቋ",
      "Submit": "ይላኩ",
      "Dear": "ውድ",
      "Close": "ዝጋ",
      "Your registration has been successfully submitted": "ምዝገባዎ በተሳካ ሁኔታ ተላከ",
      "Welcome to ECD-Adventist Messengers": "እንኳን ወደ ECD-አድቬንቲስት መልእክተኞች በደህና መጣህ",
      "Add your name to the Adventist Messenger's Ministry List!": "ስምህን ወደ መልእክተኞች አገልግሎት ዝርዝር አክል!",
      "Location and membership": "ቦታ እና አባልነት"
    },
    "ar": {
      "Registration Form": "استمارة التسجيل",
      "First Name": "الاسم الأول",
      "Middle Name (optional)": "اسم الأب (اختياري)",
      "Last Name": "اسم العائلة",
      "Gender": "الجنس",
      "Male": "ذكر",
      "Female": "أنثى",
      "Date of Birth": "تاريخ الميلاد",
      "Mobile Number": "رقم الجوال",
      "Email Address (optional)": "عنوان البريد الإلكتروني (اختياري)",
      "Profile Photo": "صورة الملف الشخصي",
      "Country": "الدولة",
      "Region": "المنطقة",
      "City": "المدينة",
      "ZIP": "الرمز البريدي",
      "Division": "القسم",
      "Union": "الاتحاد",
      "Conference/Field": "المؤتمر/الميدان",
      "Station": "المحطة",
      "District": "الحي",
      "Congregation": "الجماعة",
      "Preferred Language": "اللغة المفضلة",
      "Are you a regular participant in the Adventist community?": "هل أنت مشارك منتظم في مجتمع المعمدانيين؟",
      "Are you already baptized as a regular member of the Adventist Church?": "هل تم تعميدك بالفعل كعضو منتظم في الكنيسة المعمدانية؟",
      "If not, do you expect to be baptized in the future?": "إذا لم يكن كذلك، هل تتوقع أن تُعمد في المستقبل؟",
      "Select": "اختر",
      "Yes": "نعم",
      "No": "لا",
      "Language": "اللغة",
      "Submit": "إرسال",
      "Dear": "عزيزي/عزيزتي",
      "Close": "إغلاق",
      "Your registration has been successfully submitted": "تم إرسال تسجيلك بنجاح",
      "Welcome to ECD-Adventist Messengers": "مرحبًا بك في رسل الأدفنتست لمنطقة ECD",
      "Add your name to the Adventist Messenger's Ministry List!": "أضف اسمك إلى قائمة خدمة رسل الأدفنتست!",
      "Location and membership": "الموقع والعضوية"
    },
    "lg": {
      "Registration Form": "Foomu y'Okwewandiisa",
      "First Name": "Erinnya Lya Ntandikwa",
      "Middle Name (optional)": "Erinnya Lya Wakati (Ky'okweraliikiriza)",
      "Last Name": "Erinnya Lya Mabweggenza",
      "Gender": "Obusajja n'Obukazi",
      "Male": "Omusajja",
      "Female": "Omukazi",
      "Date of Birth": "Ennaku y'Okuzalibwa",
      "Mobile Number": "Namba ya Ssimu",
      "Email Address (optional)": "Endagiriro ya Email (Ky'okweraliikiriza)",
      "Profile Photo": "Ekifaananyi Kyo",
      "Country": "Eggwanga",
      "Region": "Kitundu",
      "City": "Kibuga",
      "ZIP": "Koodi ya Pposta",
      "Division": "Ebibiina",
      "Union": "Ekkooti",
      "Conference/Field": "Olukiiko/Oluwummula",
      "Station": "Ssiteegi",
      "District": "Disitulikiti",
      "Congregation": "Kkanisa",
      "Preferred Language": "Olulimi Olw'Okwagala",
      "Are you a regular participant in the Adventist community?": "Oli mweyongerayo mu kkubo lya Adventist bulijjo?",
      "Are you already baptized as a regular member of the Adventist Church?": "Oli mubatiziddwa nga omu ku bakristaayo ba Adventist?",
      "Select": "Londa",
      "Yes": "Yee",
      "No": "Nedda",
      "Language": "Olulimi",
      "Submit": "Tumya",
      "Dear": "Omwagalwa",
      "Close": "Ggalawo",
      "Your registration has been successfully submitted": "Okwewandiisa kwo kusindikiddwa bulungi",
      "Welcome to ECD-Adventist Messengers": "Tukusanyukidde mu Babbaka ba ECD-ABAAdventist",
      "Add your name to the Adventist Messenger's Ministry List!": "Gatta erinnya lyo ku Lisi y’Ababaka ba ABAAdventist!",
      "Location and membership": "Ekifo n'obwenkanya"
    },
    "ln": {
      "Registration Form": "Lola ya koponami",
      "First Name": "Nkombo ya liboso",
      "Middle Name (optional)": "Nkombo ya mobali (esengeli te)",
      "Last Name": "Nkombo ya familia",
      "Gender": "Soki",
      "Male": "Mobali",
      "Female": "Mwaka",
      "Date of Birth": "Mozindo ya kobota",
      "Mobile Number": "Noméro ya telefoni",
      "Email Address (optional)": "Adresse e-mail (esengeli te)",
      "Profile Photo": "Liko ya profil",
      "Country": "Mokili",
      "Region": "Ebandeli",
      "City": "Lubumbashi",
      "ZIP": "Nkombo ya mokili",
      "Division": "Division",
      "Union": "Union",
      "Conference/Field": "Kongres/Espace",
      "Station": "Liyambo",
      "District": "Distrik",
      "Congregation": "Kongregasyon",
      "Preferred Language": "Lingala ya esengo",
      "Are you a regular participant in the Adventist community?": "Ozali moto ya kokota na biso ya komunité adventiste?",
      "Are you already baptized as a regular member of the Adventist Church?": "Ozozali kokota na nzela ya mobulu ya Église adventiste?",
      "If not, do you expect to be baptized in the future?": "Soki te, ozali na esengo ya kokota na mobulu na nsima?",
      "Select": "Tala",
      "Yes": "Oui",
      "No": "Non",
      "Language": "Lingala",
      "Submit": "Sumbula",
      "Dear": "Bolingo",
      "Close": "Kokisa",
      "Your registration has been successfully submitted": "Etanda na yo epesami na bonsomi",
      "Welcome to ECD-Adventist Messengers": "Boyei malamu na ECD-Batindami ya BaAdventiste",
      "Add your name to the Adventist Messenger's Ministry List!": "Bakisa nkombo na yo na liste ya mosala ya Batindami ya Adventiste!",
      "Location and membership": "Esika mpe boyokani"
    },
    "so": {
      "Registration Form": "Foomka Diiwaangelinta",
      "First Name": "Magaca Hore",
      "Middle Name (optional)": "Magaca Dhexe (ikhtiyaar)",
      "Last Name": "Magaca Qoyska",
      "Gender": "Jinsiga",
      "Male": "Rag",
      "Female": "Dumar",
      "Date of Birth": "Taariikhda Dhalashada",
      "Mobile Number": "Lambarka Mobaylka",
      "Email Address (optional)": "Cinwaanka Emailka (ikhtiyaar)",
      "Profile Photo": "Sawirka Profile",
      "Country": "Dalka",
      "Region": "Gobolka",
      "City": "Magaalada",
      "ZIP": "Koodhka Boostada",
      "Division": "Qaybta",
      "Union": "Isbahaysiga",
      "Conference/Field": "Shirka/Meydka",
      "Station": "Saldhigga",
      "District": "Degmada",
      "Congregation": "Kaniisadda",
      "Preferred Language": "Luuqada La Doorto",
      "Are you a regular participant in the Adventist community?": "Ma tahay ka qaybqaate joogto ah oo ka tirsan bulshada Adventist?",
      "Are you already baptized as a regular member of the Adventist Church?": "Ma tahay qof horey loogu baahiyay xubin joogto ah oo ka tirsan Kaniisadda Adventist?",
      "Select": "Dooro",
      "Yes": "Haa",
      "No": "Maya",
      "Language": "Luuqad",
      "Submit": "Dir",
      "Dear": "Gacaliye/Gacaliso",
      "Close": "Xir",
      "Your registration has been successfully submitted": "Diiwaangelintaada si guul leh ayaa loo gudbiyay",
      "Welcome to ECD-Adventist Messengers": "Ku soo dhawoow ECD-Adventist Messengers",
      "Add your name to the Adventist Messenger's Ministry List!": "Ku dar magacaaga Liiska Adeegga Wariyeyaasha Adventist!",
      "Location and membership": "Goobta iyo xubinnimada"

    }
  }
};
export const unions = {
  "East-Central Africa Division": [
    { label: "Burundi Union Mission", value: "Burundi Union Mission" },
    { label: "Ethiopia Union Mission", value: "Ethiopia Union Mission" },
    { label: "Kenya West Union Conference", value: "Kenya West Union Conference" },
    { label: "Kenya East Union Conference", value: "Kenya East Union Conference" },
    { label: "Rwanda Union Mission", value: "Rwanda Union Mission" },
    { label: "South Sudan Field", value: "South Sudan Field" },
    { label: "Sudan Field", value: "Sudan Field" },
    { label: "Tanzania Union Mission", value: "Tanzania Union Mission" },
    { label: "Uganda Union Mission", value: "Uganda Union Mission" }
  ]
}
export const conferances = {
  "Burundi Union Mission": [
    { label: "Burundi East Conference", value: "Burundi East Conference" },
    { label: "Burundi West Conference", value: "Burundi West Conference" }
  ],
  "Ethiopia Union Mission": [
    { label: "Ethiopia North Conference", value: "Ethiopia North Conference" },
    { label: "Ethiopia South Conference", value: "Ethiopia South Conference" }
  ],
  "Kenya West Union Conference": [
    { label: "Central Kenya Conference", value: "Central Kenya Conference" },
    { label: "North Kenya Conference", value: "North Kenya Conference" },
    { label: "South Kenya Conference", value: "South Kenya Conference" }
  ],
  "Kenya East Union Conference": [
    { label: "Eastern Kenya Conference", value: "Eastern Kenya Conference" },
    { label: "Nairobi City Conference", value: "Nairobi City Conference" }
  ],
  "Rwanda Union Mission": [
    { label: "Northern Rwanda Field", value: "Northern Rwanda Field" },
    { label: "Southern Rwanda Field", value: "Southern Rwanda Field" }
  ],
  // Add other unions and their respective conferences here
}
export const Languages = [
  { label: "English", value: "en" },
  { label: "French", value: "fr" },
  { label: "Swahili", value: "sw" },
  { label: "Kinyarwanda", value: "rw" },
  { label: "Amharic", value: "am" },
  { label: "Arabic", value: "ar" },
  { label: "Lingala", value: "ln" },
  { label: "Somali", value: "so" }
]